kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo= #"root"encoded to base64 as computer can read binary file
   
#Output:

1. create secret
  kubectl apply -f secrets.yml 
  secret/mysql-secret created

2. view secret
  kubectl get secret -n mysql
  NAME           TYPE     DATA   AGE
  mysql-secret   Opaque   1      2s
