kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql

spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef: 
              name: mysql-config-map
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      storageClassName: local-path
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

#Output:

1. create with configmap
  kubectl apply -f statefulset.yml 
  statefulset.apps/mysql-statefulset created

2. get pods
  kubectl get pods -n mysql
  NAME                  READY   STATUS    RESTARTS   AGE
  mysql-statefulset-0   1/1     Running   0          2m59s
  mysql-statefulset-1   1/1     Running   0          2m54s
  mysql-statefulset-2   1/1     Running   0          2m49s

3. 
