kind: ServiceAccount
apiVersion: v1
metadata:
  name: apache-user
  namespace: apache

#Output:

1. create service account
  kubectl apply -f service-account.yml 
  serviceaccount/apache-user created

2. view service accounts
  kubectl get serviceaccount -n apache
  NAME          SECRETS   AGE
  apache-user   0         19s
  default       0         22m

3. 
